### ISSUE TITLE
Certain Treesitter grammars give errors

### ISSUE THREAD

**Issue by colin-heffernan** [jordanisaacs/neovim-flake#20]
I use my own Neovim flake based on this one, but the problem applies here as well: certain grammars are no longer working. Specifically, Typescript is a buggy mess. Opening a `.ts` file lights up the screen with red. Is this an issue with the flake, or is it an incompatibility between the grammars and a newer version of Treesitter, or is it something else entirely?

**Comment by jordanisaacs** [comment]
What's the output of :checkhealth for the grammars. The typescript grammar package is broken on the version of nixpkgs used by the flake. All other grammars should work. If this is the issue then try setting the `treesitter.grammar` option with a different version of the typescript grammar.

The second case may be that the versions of the treesitter grammar provided by nixpkgs you are using are not compatible with the pinned version of nvim-treesitter. Thus you should do a flake follows and grab the most recent version of nvim treesitter to override.

**Comment by colin-heffernan** [comment]
The only parsers giving errors are TypeScript and Bash, with 18 other parsers working fine. As for nvim-treesitter, I already follow master. Should I build the grammars from source instead of following Nixpkgs?

**Comment by jordanisaacs** [comment]
Ya I would try that. Treesitter grammar versions are very finicky. I recently refactored the flake specifically so you could specify grammars yourself.

**Comment by jordanisaacs** [comment]
Should be fixed now that the flake has switched to using nvim-treesitter pinned grammars and the nixpkgs version of the plugin: https://github.com/jordanisaacs/neovim-flake/commit/7a6d7a144bee2a2d300a1a362c822afe47bbe4dd.
