### ISSUE TITLE
Enabling visuals.lspkind.enable without enabling visuals.enable leads to broken config with completion.

### ISSUE THREAD

**Issue by MonaMayrhofer** [jordanisaacs/neovim-flake#35]
When one enables lspkind and completion but forgets to enable visuals, this yields a broken config.

```nix
{
  visuals.lspkind.enable=true;
  autocomplete.enable=true;
}
```

The completion module
https://github.com/jordanisaacs/neovim-flake/blob/f2812360ab8915c1e96cc3150a4f4efa4d034fa7/modules/completion/default.nix#L108-L109 calls `require'lspkind'` whenever `visuals.lspkind.enable=true`, but the lspkind plugin is only loaded if both `visuals.enable` and `visuals.lspkind.enable` are true:
https://github.com/jordanisaacs/neovim-flake/blob/f2812360ab8915c1e96cc3150a4f4efa4d034fa7/modules/visuals/visuals.nix#L67-L80

One could argue that `visuals.enable` should be either automatically enabled if `visuals.lspkind` is enabled, or not exist at all.

**Comment by jordanisaacs** [comment]
Thanks for this detailed report, helped me write a fix fast. `lspkind` belongs more under `lsp` than visuals so I moved it there (and `lsp` gets automatically enabled when in use). Formatting completion is much more configurable/robust now. Also, gave me a reason to touch those files and give them a much needed clean up.
