### ISSUE TITLE
x86_64-linux only?

### ISSUE THREAD

**Issue by gador** [jordanisaacs/neovim-flake#6]
Hi,

I use your flake and neovim config and I like it a lot. Thanks!

Can you eleborate why you force the use ov `x86_64-linux` system now in https://github.com/jordanisaacs/neovim-flake/commit/d5fc2d3e23dcb4f1dd7c55ded2e0f431d84653ea ?
I used your flake successfully on my raspberry and due to the recent change, I can't use it anymore..

**Comment by jordanisaacs** [comment]
Hi gador,

Sorry for the late reply, been on midterms and break recently. I packaged a treesitter plugin for a language that currently only builds on x86-64 linux (`tree-sitter-hare` in my jdpkgs repo). Thus it would fail `nix flake check` and I am working on getting all my flakes to pass. Feel free to fork it, reintroduce the flake-utils and remove the dependency on jdpkgs and it should work just fine!

- Jordan

**Comment by gador** [comment]
Hi Jordan,
thanks for the pointers! I ended up using an older revision and then later switched to https://github.com/pta2002/nixvim
Thanks for all the work you put into this!
