### ISSUE TITLE
Materialize `init` file from neovimBuilder

### ISSUE THREAD

**Issue by pplanel** [jordanisaacs/neovim-flake#8]
Hello, thanks for the flake, its perfect! So perfect that some peers want me to share the plugins, init file and so on. (they are not still ready for nix)
I'm still learning how to build and work on flakes and i had no success creating a flake package based on the neovim package in the same flake. Actually I cannot find the init file in my own system.
I'm pretty sure i'm missing something, can u shed some light in this?

**Comment by pplanel** [comment]
Found it in its own derivation, how so?

**Comment by jordanisaacs** [comment]
So the init file is actually a file in the nix store auto generated from my lib function. When you call `nvim` you are actually calling a wrapper around raw neovim. See how [nixpkgs](https://github.com/NixOS/nixpkgs/blob/53bc699e2c9bf49d747089f9a56260ab1c163d52/pkgs/applications/editors/neovim/wrapper.nix#L48) is providing `-u ${writeText "init.vim" neovimRcContent}`.  See [nix cookbook](https://nixos.wiki/wiki/Nix_Cookbook#Wrapping_packages) for how wrapping packages works.

**Comment by jordanisaacs** [comment]
See the [builder](https://github.com/jordanisaacs/neovim-flake/blob/main/lib/neovimBuilder.nix). What is happening is I evaluate all my modules to produce a `customRc`, and my list of plugins. Then I just pass it into the nixpkgs builder function. The conversion of the module to a vim file happens in [modules/core](https://github.com/jordanisaacs/neovim-flake/blob/main/modules/core/default.nix)

**Comment by pplanel** [comment]
Ohhh, nice! Much appreciated! Thanks again!
